import {LanguageUser} from './userLanguage';

export const LanguageUsers: LanguageUser[] =[
    {
      name:'umesh',
      language:'Polish',
      noOfFile:132321
    },
    {
        name:'rahil',
        language:'English',
        noOfFile:14
    },
    {
        name:'sandeep',
        language:'English',
        noOfFile:40
    },
    {
        name:'isha',
        language:'English',
        noOfFile:21
    },
    {
        name:'nj',
        language:'English',
        noOfFile:43
    },
    {
        name:'rahil',
        language:'English',
        noOfFile:150
    },
    {
        name:'ankil',
        language:'English',
        noOfFile:154
    },
    {
        name:'hitesh',
        language:'English',
        noOfFile:11
    },
    {
        name:'rahul',
        language:'Hindi',
        noOfFile:111
      },
      {
          name:'sanket',
          language:'Hindi',
          noOfFile:110
      }
      ,
      {
          name:'piyush',
          language:'English',
          noOfFile:110
      },
      {
        name:'ashraf',
        language:'English',
        noOfFile:110
       },
        {
        name:'abhishek',
        language:'English',
        noOfFile:110
        },
        {
            name:'prakash',
            language:'English',
            noOfFile:110
        }, 
        {
            name:'aurangzeb',
            language:'English',
            noOfFile:110
        }, 
      {
        name:'richa',
        language:'English',
        noOfFile:103
      },
      {
          name:'Suvom',
          language:'Telugu',
          noOfFile:3
      }
]